20220509
<학습목표>
1.Stored Procedure 저장프로시저
2.User Function 사용자 정의함수
 
--STORED(오라클 서버의 캐시공간에 미리 저장된) PROCEDURE
--업데이트 쎄(SET)대여(WHERE)
SELECT PROD_ID, PROD_TOTALSTOCK
FROM   PROD
WHERE  PROD_ID = 'P101000001';
/
CREATE OR REPLACE PROCEDURE USP_PROD_TOTALSTOCK_UPDATE
(P_PROD_ID IN VARCHAR2, P_PROD_TOTALSTOCK IN NUMBER)
IS
BEGIN
    UPDATE PROD
    SET    PROD_TOTALSTOCK = PROD_TOTALSTOCK + P_PROD_TOTALSTOCK
    WHERE  PROD_ID = P_PROD_ID;
    DBMS_OUTPUT.PUT_LINE('업데이트 성공!');
    COMMIT;
END;
/
--EXECUTE USP_PROD_TOTALSTOCK_UPDATE;
EXEC USP_PROD_TOTALSTOCK_UPDATE('P201000002', 20);
/
SELECT PROD_ID, PROD_NAME, PROD_TOTALSTOCK
FROM   PROD
WHERE  PROD_ID = 'P201000002';
/
SET SERVEROUTPUT ON;
/
--회원아이디를 입력받아 이름과 취미를 OUT 매개변수로 처리해보자
CREATE OR REPLACE PROCEDURE USP_GET_MEMBER
(P_MEM_ID IN VARCHAR2, V_NAME OUT VARCHAR2, V_LIKE OUT VARCHAR2)
IS
BEGIN
    SELECT MEM_NAME, MEM_LIKE INTO V_NAME, V_LIKE
    FROM   MEMBER
    WHERE  MEM_ID = P_MEM_ID;
END;
/
VAR MEM_NAME VARCHAR2(20)
VAR MEM_LIKE VARCHAR2(20)
EXEC USP_GET_MEMBER('c001', :MEM_NAME, :MEM_LIKE)
PRINT MEM_NAME
PRINT MEM_LIKE;
/

--회원별 
--구매금액의 합 : SUM(PROD_SALE * CART_QTY)
--을 구하는 쿼리를 만들어보자
--이 중에서 구매금액의 합이 가장 많은 1명만 출력해보자
--ALIAS : MEM_NAME, MEM_AMT
CREATE OR REPLACE PROCEDURE USP_MEM_TOP
(P_YEAR IN VARCHAR2, P_MEM_NAME OUT VARCHAR2, P_MEM_AMT OUT NUMBER)
IS
BEGIN
    SELECT T.MEM_NAME, T.MEM_AMT INTO P_MEM_NAME, P_MEM_AMT
    FROM 
    (
        SELECT M.MEM_NAME
             , SUM(P.PROD_SALE * C.CART_QTY) MEM_AMT
        FROM   PROD P, CART C, MEMBER M
        WHERE  P.PROD_ID = C.CART_PROD
        AND    C.CART_MEMBER = M.MEM_ID
        AND    C.CART_NO LIKE P_YEAR || '%'
        GROUP BY M.MEM_NAME
        ORDER BY SUM(P.PROD_SALE * C.CART_QTY) DESC
    ) T
    WHERE  ROWNUM <= 1;
END;
/
VAR P_MEM_NAME VARCHAR2
VAR P_MEM_AMT  NUMBER
EXEC USP_MEM_TOP('2020', :P_MEM_NAME, :P_MEM_AMT)
PRINT P_MEM_NAME
PRINT P_MEM_AMT;
/
--상품코드와 월을 입력하면 해당 월에 대한 해당 상품의 입고, 출고를 처리해 화면에 출력해보자
--(프로시저명 : USP_PRO_INFO, 월 형식은 YYYYMM이라 가정, 입고 및 출고는 OUT  매개변수로 처리



